### ISSUE TITLE
Send to multiple emails

### ISSUE THREAD

**Issue by Manishfoodtechs** [lexoyo/serverless-forms#1]
Serverless-forms is wonderful work. However,

1) I want to know how I can send emails to multiple people.

2) One of my form field is email. I want to send a copy to form filler too.

**Comment by lexoyo** [comment]
Hi @Manishfoodtechs 
These are good ideas
Would you like me to explain where to change the code?

**Comment by lexoyo** [comment]
> I want to know how I can send emails to multiple people.

Implemented and documented in the readme

> One of my form field is email. I want to send a copy to form filler too.

In the roadmap in the readme
